/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRiwayatRouteImport } from './routes/_authenticated/riwayat'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedRiwayatIdRouteImport } from './routes/_authenticated/riwayat.$id'
import { Route as AuthenticatedAdminSekolahRouteImport } from './routes/_authenticated/admin.sekolah'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin.dashboard'
import { Route as AuthenticatedAdminAbsensiRouteImport } from './routes/_authenticated/admin.absensi'
import { Route as AuthenticatedAdminPengajarIdRouteImport } from './routes/_authenticated/admin.pengajar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiwayatRoute = AuthenticatedRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedRiwayatIdRoute = AuthenticatedRiwayatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedRiwayatRoute,
} as any)
const AuthenticatedAdminSekolahRoute =
  AuthenticatedAdminSekolahRouteImport.update({
    id: '/sekolah',
    path: '/sekolah',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAbsensiRoute =
  AuthenticatedAdminAbsensiRouteImport.update({
    id: '/absensi',
    path: '/absensi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPengajarIdRoute =
  AuthenticatedAdminPengajarIdRouteImport.update({
    id: '/pengajar/$id',
    path: '/pengajar/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/riwayat': typeof AuthenticatedRiwayatRouteWithChildren
  '/admin/absensi': typeof AuthenticatedAdminAbsensiRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/sekolah': typeof AuthenticatedAdminSekolahRoute
  '/riwayat/$id': typeof AuthenticatedRiwayatIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pengajar/$id': typeof AuthenticatedAdminPengajarIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/riwayat': typeof AuthenticatedRiwayatRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/admin/absensi': typeof AuthenticatedAdminAbsensiRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/sekolah': typeof AuthenticatedAdminSekolahRoute
  '/riwayat/$id': typeof AuthenticatedRiwayatIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pengajar/$id': typeof AuthenticatedAdminPengajarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/riwayat': typeof AuthenticatedRiwayatRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/absensi': typeof AuthenticatedAdminAbsensiRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/sekolah': typeof AuthenticatedAdminSekolahRoute
  '/_authenticated/riwayat/$id': typeof AuthenticatedRiwayatIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pengajar/$id': typeof AuthenticatedAdminPengajarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/profile'
    | '/riwayat'
    | '/admin/absensi'
    | '/admin/dashboard'
    | '/admin/sekolah'
    | '/riwayat/$id'
    | '/admin/'
    | '/admin/pengajar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/profile'
    | '/riwayat'
    | '/'
    | '/admin/absensi'
    | '/admin/dashboard'
    | '/admin/sekolah'
    | '/riwayat/$id'
    | '/admin'
    | '/admin/pengajar/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/profile'
    | '/_authenticated/riwayat'
    | '/_authenticated/'
    | '/_authenticated/admin/absensi'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/sekolah'
    | '/_authenticated/riwayat/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pengajar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riwayat': {
      id: '/_authenticated/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof AuthenticatedRiwayatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/riwayat/$id': {
      id: '/_authenticated/riwayat/$id'
      path: '/$id'
      fullPath: '/riwayat/$id'
      preLoaderRoute: typeof AuthenticatedRiwayatIdRouteImport
      parentRoute: typeof AuthenticatedRiwayatRoute
    }
    '/_authenticated/admin/sekolah': {
      id: '/_authenticated/admin/sekolah'
      path: '/sekolah'
      fullPath: '/admin/sekolah'
      preLoaderRoute: typeof AuthenticatedAdminSekolahRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/absensi': {
      id: '/_authenticated/admin/absensi'
      path: '/absensi'
      fullPath: '/admin/absensi'
      preLoaderRoute: typeof AuthenticatedAdminAbsensiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pengajar/$id': {
      id: '/_authenticated/admin/pengajar/$id'
      path: '/pengajar/$id'
      fullPath: '/admin/pengajar/$id'
      preLoaderRoute: typeof AuthenticatedAdminPengajarIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAbsensiRoute: typeof AuthenticatedAdminAbsensiRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminSekolahRoute: typeof AuthenticatedAdminSekolahRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPengajarIdRoute: typeof AuthenticatedAdminPengajarIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAbsensiRoute: AuthenticatedAdminAbsensiRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminSekolahRoute: AuthenticatedAdminSekolahRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPengajarIdRoute: AuthenticatedAdminPengajarIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRiwayatRouteChildren {
  AuthenticatedRiwayatIdRoute: typeof AuthenticatedRiwayatIdRoute
}

const AuthenticatedRiwayatRouteChildren: AuthenticatedRiwayatRouteChildren = {
  AuthenticatedRiwayatIdRoute: AuthenticatedRiwayatIdRoute,
}

const AuthenticatedRiwayatRouteWithChildren =
  AuthenticatedRiwayatRoute._addFileChildren(AuthenticatedRiwayatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRiwayatRoute: typeof AuthenticatedRiwayatRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRiwayatRoute: AuthenticatedRiwayatRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
